package:
    type:           library
    name:           omnipay-paypal
    namespace:      Omnipay\PayPal
    headline:       'Omnipay: PayPal'
    title:          PayPal driver for Omnipay PHP payment library
    license:        MIT
    keywords:       php, paypal, merchant
    year:           2015
    description:    |
        [Omnipay](https://github.com/omnipay/omnipay) is a framework agnostic, multi-gateway payment
        processing library for PHP 5.3+.
        This package implements [PayPal](https://paypal.com/) support for Omnipay.

require:
    hiqdev/hidev-php:    "*"
    hiqdev/hidev-vendor: "*"
