package:
    type:           library
    name:           omnipay-paypal
    title:          PayPal driver for Omnipay PHP payment library
    license:        MIT
    headline:       'Omnipay: PayPal'
    keywords:       php, paypal, merchant
    namespace:      Omnipay\PayPal
    description:    |
        [Omnipay](https://github.com/omnipay/omnipay) is a framework agnostic, multi-gateway payment
        processing library for PHP 5.3+.

        This package implements [PayPal](https://paypal.com/) support for Omnipay.

require:
    hiqdev/hidev-php:    "*"
    hiqdev/hidev-vendor: "*"
