package:
    name:           omnipay-paypal
    namespace:      hiqdev\php\merchant\paypal
    headline:       Omnipay: PayPal
    title:          PayPal driver for Omnipay PHP payment library
    type:           library
    license:        MIT
    keywords:       php, paypal, merchant
    description:    |
        [Omnipay](https://github.com/omnipay/omnipay) is a framework agnostic, multi-gateway payment
        processing library for PHP 5.3+.
        This package implements [PayPal](https://paypal.com/) support for Omnipay.

require:
    hiqdev/hidev-config:        "*"
    hiqdev/hidev-config-php:    "*"
