package:
    name:           php-merchant-paypal
    namespace:      hiqdev\php\merchant\paypal
    title:          PayPal plugin for PHP merchant library
    type:           library
    keywords:       php, paypal, merchant
    description:    |
        [PayPal](https://paypal.com/) plugin for [PHP merchant library](https://github.com/hiqdev/php-merchant).

require:
    hiqdev/hidev-config:        "*"
    hiqdev/hidev-config-php:    "*"
